{{- range $name, $model := .Values.catalog}}
{{- if or $model.enabled $.Values.all.enabled }}
---
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: {{ $name }}
  {{- with $model.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $model.features }}
  features:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $model.owner }}
  owner: {{ . }}
  {{- end }}
  url: {{ $model.url }}
  {{- with $model.adapters }}
  adapters:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $model.engine }}
  engine: {{ . }}
  {{- end }}
  {{- with $model.args }}
  args:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $model.env }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  minReplicas: {{ default 0 $model.minReplicas }}
  {{- with $model.maxReplicas }}
  maxReplicas: {{ . }}
  {{- end}}
  {{- with $model.targetRequests }}
  targetRequests: {{ . }}
  {{- end}}
  {{- with $model.scaleDownDelaySeconds }}
  scaleDownDelaySeconds: {{ . }}
  {{- end}}
  {{- with $model.resourceProfile }}
  resourceProfile: {{ . }}
  {{- end}}
  {{- with $model.cacheProfile }}
  cacheProfile: {{ . }}
  {{- end}}
  {{- with $model.files }}
  files:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .replicas }}
  replicas: {{ .replicas }}
  {{- end }}

  {{- if ne .autoscalingDisabled nil }}
  autoscalingDisabled: {{ .autoscalingDisabled }}
  {{- end }}

  {{- if .image }}
  image: {{ .image | quote }}
  {{- end }}

  {{- if .envFrom }}
  envFrom:
    {{- toYaml .envFrom | nindent 4 }}
  {{- end }}

  {{- if .priorityClassName }}
  priorityClassName: {{ .priorityClassName | quote }}
  {{- end }}

  {{- with .loadBalancing }}
  loadBalancing:
    {{- if .strategy }}
    strategy: {{ .strategy | quote }}
    {{- end }}
    {{- with .prefixHash }}
    prefixHash:
      {{- if .salt }}
      salt: {{ .salt | quote }}
      {{- end }}
      {{- if .header }}
      header: {{ .header | quote }}
      {{- end }}
      {{- if .queryParam }}
      queryParam: {{ .queryParam | quote }}
      {{- end }}
      {{- if .cookie }}
      cookie: {{ .cookie | quote }}
      {{- end }}
      {{- if .fixed }}
      fixed: {{ .fixed | quote }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- end}}
{{- end}}
